### ISSUE TITLE
Default value for the position column?

### ISSUE THREAD

**Issue by alexhanh** [brendon/ranked-model#32]
Seems like nil values should be avoided for the position column to avoid problems with ranked_model. (IMHO This should be mentioned in docs!)

Would this be the recommended practice assuming we would want new items to be at the bottom as default?

``` ruby
t.integer :sort_order, :default => RankedModel::MAX_RANK_VALUE
```

**Comment by donatoaz** [comment]
I know this is an old issue, however I am trying to find out what to do when I add raking to an already existing resource.

Should I have done an update on all records setting them to RankedModel::MAX_RANK_VALUE ?

**Comment by donatoaz** [comment]
It's been a long time, but I believe what I did was to run inside the migration an update setting the values to an incremental value evenly spaced apart by RankedModel::MAX_RANK_VALUE / MyModel.count. Since my tables were not so big, I had no performance issues. But be aware that if you are running against a table with, perhaps, millions of records that you might have issues.

If you decide to go along this path, just remember this: https://blog.makandra.com/2010/03/how-to-use-models-in-your-migrations-without-killing-kittens/

**Comment by dylan-snyder** [comment]
Thanks for the comment. For me, this was my solution:

```
class AddSortId < ActiveRecord::Migration[5.0]
  def up
    add_column :items, :sort_order, :integer

    table_name = "items"
    execute "UPDATE #{table_name} SET sort_order = id;"
  end

  def down
    remove_column :items, :sort_id
  end
end
```
This is similar to other proposed solutions above, where the sort_order matches the id at first. I haven't had any problems with this so far, but I am also working on old code with a bunch of hackey code invovled, so this might not be a one-size-fits-all solution.

**Comment by brendon** [comment]
Closing. I added a check for this on boot.
